server:
  port: 8000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jonchan/SpringCloudSimpleForSpringIO-config.git
          search-paths: /**
          default-label: master
          # basedir: E:\\Study\\SpringCloudSimpleForSpringIO-config
          proxy:
            https:
              host: 192.168.13.19
              password: 759282337@ffcs
              port: 7777
              username: chenjunlai
              # nonProxyHosts: example.com
