server:
  port: 8000
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/jonchan/SpringCloudSimpleForSpringIO-config.git
          search-paths: /**
          default-label: master
          # basedir: E:\\Study\\SpringCloudSimpleForSpringIO-config
